### ISSUE TITLE
Could not process file

### ISSUE THREAD

**Issue by waqdev786** [rectorphp/rector-cakephp#8]
Hi,
I am trying to upgrade from Cakephp 3.5 to 3.6 but i am getting below error for each file 

 [ERROR] Could not process "src/Controller/VersionsController.php" file, due to:
         "PHPStan\BetterReflection\Reflection\ReflectionClass "Cake\Controller\Controller" could not be found in the
         located source". On line: 24

**Comment by waqdev786** [comment]
Thanks, I have invited you for repository name **rectorrep**. Please accept the invitation. 
Thank you for your help

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. We're narrowing issues to keep focus on active and engaging contributor to keep project growing. Thank you for understanding.

Feel free to re-open with failing test case.
